# Generated by Django 4.0.3 on 2024-07-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_alter_question_expiry_date_alter_question_push'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
