# Generated by Django 4.0.3 on 2024-07-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_alter_question_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='issued_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
